# Generated by MSL Maya Gate - do not edit; edit the "userSetup" tab instead.
import io
import traceback

_msl_gate_script = 'H:\\ProjectsDev\\MSL_Others\\msl_tools\\configs\\desktop\\maya_gate\\user_setup\\Dev.py'
try:
    with io.open(_msl_gate_script, encoding="utf-8") as _msl_gate_file:
        exec(compile(_msl_gate_file.read(), _msl_gate_script, "exec"), globals())
except Exception:
    print("MSL Maya Gate: userSetup script failed: " + _msl_gate_script)
    traceback.print_exc()
