# tools/desktop/maya_gate/boost.py
"""Boost start: launch Maya without the plug-ins an environment switched off.

Qt-free: the tab (boost_tab.py) edits, this module knows Maya's side.

How it works. Maya loads its "Auto load" plug-ins at startup — dozens of
them, most of the startup time. A boosted launch:

1. starts Maya with its own `-noAutoloadPlugins` flag (nothing is auto-loaded),
2. puts a small userSetup.py on PYTHONPATH (Maya runs every userSetup.py it
   finds, see user_setup.py) that loads the plug-ins of Maya's autoload
   list EXCEPT the environment's skipped ones, timing each.

Maya's own settings are not edited — and must be actively protected: a Maya
started with -noAutoloadPlugins REWRITES prefs/pluginPrefs.mel on exit with
only the plug-ins that carry the autoload flag in that session (measured
with Maya 2025: 44 entries -> 1). So the userSetup first flags EVERY plug-in
of the original list for autoload — by its file path, which works without
loading it (`pluginInfo -edit -autoload true <path>`; by name it only works
for loaded plug-ins) — and Maya then writes the complete list back. A
plug-in whose file can't be found is loaded anyway rather than dropped.
Consequences:
- never pass the flag when the userSetup can't run (MAYA_SKIP_USERSETUP_PY);
- never pass it to a Maya that has no pluginPrefs.mel yet (a fresh
  preferences folder, e.g. a new MAYA_APP_DIR): there is no list to load
  from, and Maya would save a near-empty one instead of its defaults — the
  first start there is a normal one (page._launch checks autoload_plugins());
- every boosted launch first stores a copy of pluginPrefs.mel
  (boost/backup/<year>/), restorable from the tab.

A scene that needs a skipped plug-in still loads it on open (Maya honors
the file's `requires`); the Plug-in Manager loads anything by hand.

The userSetup's content never changes (parameters travel as environment
variables), so Maya 2022+ asks to trust it once. It must stay Python-2.7-
valid (Maya 2020).

Startup time. The same loader is on PYTHONPATH in EVERY launch from Maya
Gate (boosted or not) and notes when Maya became ready: Maya Gate writes a
small file per launch (LaunchLog: when the tile was clicked, which Maya,
which environment, boosted or not), the loader adds `ready_seconds` to it
from a lowest-priority evalDeferred — the first moment Maya is idle after
its startup work, plug-in loading included. Without a userSetup
(MAYA_SKIP_USERSETUP_PY) there is no measurement.

Layout under the tool's config folder:
    boost/launch/userSetup.py          the generated loader (on PYTHONPATH)
    boost/launches/<stamp>_<year>.json one per launch: what was started, how long it took
    boost/report_<year>.json           what the last boosted start loaded, and how long each took
    boost/backup/<year>/pluginPrefs_<stamp>.mel
"""
import json
import os
import shutil
import time
from pathlib import Path
from typing import Mapping

from msl_tools.msl.core.fs.maya_paths import MayaPaths

_QUOTE = '\\"'  # \" as written inside pluginPrefs.mel

_LOADER = r'''# Generated by MSL Maya Gate - do not edit.
# 1. Boost start: loads Maya's auto-load plug-ins except the ones this launch skips,
#    and keeps Maya's own auto-load list intact. Only in a launch that asks for it.
# 2. Notes how long Maya took to become ready, for Maya Gate's "Boost start" tab.
import json
import os
import time
import traceback


_msl_gate_plugin_seconds = [None]


def _msl_gate_ready():
    """Maya is idle after its startup work: store the time since the click in Maya Gate."""
    target = os.environ.get("MSL_GATE_LAUNCH_FILE", "")
    clicked = os.environ.get("MSL_GATE_LAUNCH_TIME", "")
    if not target or not clicked:
        return
    try:
        data = {}
        if os.path.isfile(target):
            with open(target) as handle:
                data = json.load(handle)
        data["ready_seconds"] = round(time.time() - float(clicked), 2)
        if _msl_gate_plugin_seconds[0] is not None:
            data["plugin_seconds"] = _msl_gate_plugin_seconds[0]
        with open(target, "w") as handle:
            json.dump(data, handle, indent=1)
    except Exception:
        traceback.print_exc()


def _msl_gate_boost():
    import maya.cmds as cmds

    quote = chr(92) + '"'
    skip = set(name for name in os.environ.get("MSL_GATE_BOOST_SKIP", "").split(os.pathsep) if name)
    report = {"plugins": {}, "order": [], "notes": [], "time": time.strftime("%Y-%m-%d %H:%M:%S"),
              "environment": os.environ.get("MSL_GATE_BOOST_ENVIRONMENT", "")}

    names = []
    prefs = os.path.join(cmds.internalVar(userPrefDir=True), "pluginPrefs.mel")
    if os.path.isfile(prefs):
        with open(prefs) as handle:
            for line in handle:
                if "autoLoadPlugin(" in line:
                    parts = line.split(quote)
                    if len(parts) >= 6 and parts[3] not in names:
                        names.append(parts[3])

    folders = [folder for folder in os.environ.get("MAYA_PLUG_IN_PATH", "").split(os.pathsep) if folder]

    def find(name):
        candidates = [name] if os.path.splitext(name)[1] else [name + ".mll", name + ".py"]
        for folder in folders:
            for candidate in candidates:
                path = os.path.join(folder, candidate)
                if os.path.isfile(path):
                    return path.replace(os.sep, "/")
        return ""

    # 1. Before anything else: flag every plug-in of the list for auto-load BY FILE
    #    (possible without loading it). Maya rewrites pluginPrefs.mel on exit from
    #    these flags - an unflagged plug-in would silently leave the user's list.
    kept = set()
    for name in names:
        try:
            path = find(name)
            if path:
                cmds.pluginInfo(path, edit=True, autoload=True)
                kept.add(name)
            else:
                report["notes"].append(name + ": file not found on MAYA_PLUG_IN_PATH - loaded instead of flagged")
        except Exception as error:
            # Maya prints its own "# Error: Invalid object or value" for this; say which plug-in it was.
            report["notes"].append(name + ": could not be flagged by file (" + str(error).strip() + ") - loaded instead")

    # 2. Load what this environment wants (and whatever couldn't be flagged).
    started = time.time()
    for name in names:
        entry = {"seconds": 0.0, "status": "skipped", "error": ""}
        if name not in skip or name not in kept:
            begin = time.time()
            try:
                if not cmds.pluginInfo(name, query=True, loaded=True):
                    cmds.loadPlugin(name, quiet=True)
                cmds.pluginInfo(name, edit=True, autoload=True)
                entry["status"] = "loaded" if name not in skip else "kept"
            except Exception as error:
                entry["status"] = "failed"
                entry["error"] = str(error).strip()
            entry["seconds"] = round(time.time() - begin, 3)
        report["plugins"][name] = entry
        report["order"].append(name)
    report["seconds"] = round(time.time() - started, 3)
    _msl_gate_plugin_seconds[0] = report["seconds"]

    target = os.environ.get("MSL_GATE_BOOST_REPORT", "")
    if target:
        try:
            with open(target, "w") as handle:
                json.dump(report, handle, indent=1)
        except Exception:
            traceback.print_exc()


try:
    import maya.cmds as _msl_gate_cmds
    _msl_gate_batch = _msl_gate_cmds.about(batch=True)
    if os.environ.get("MSL_GATE_BOOST_SKIP") is not None:
        if _msl_gate_batch:
            _msl_gate_boost()
        else:
            _msl_gate_cmds.evalDeferred(_msl_gate_boost)  # like pluginPrefs.mel's own evalDeferred
    if os.environ.get("MSL_GATE_LAUNCH_FILE") and not _msl_gate_batch:
        # Lowest priority = after everything Maya deferred for its own startup.
        _msl_gate_cmds.evalDeferred(_msl_gate_ready, lowestPriority=True)
except Exception:
    print("MSL Maya Gate: startup script failed")
    traceback.print_exc()
'''


class BoostStore:
    """Reads Maya's autoload list, prepares a boosted launch, reads back what
    the launch did."""

    SUBDIR = "boost"
    FLAG = "-noAutoloadPlugins"
    SKIP_VARIABLE = "MSL_GATE_BOOST_SKIP"            # os.pathsep-joined names; its PRESENCE switches the loader on
    REPORT_VARIABLE = "MSL_GATE_BOOST_REPORT"
    ENVIRONMENT_VARIABLE = "MSL_GATE_BOOST_ENVIRONMENT"
    BLOCKING_VARIABLE = "MAYA_SKIP_USERSETUP_PY"     # with it the loader never runs: boosting would empty Maya's list
    BACKUPS_KEPT = 5

    # Plug-in families that cost the most at startup ("Heavy off" switches them off).
    # Names as Maya lists them in pluginPrefs.mel.
    HEAVY: dict[str, tuple[str, ...]] = {
        "Bifrost": ("bifrostGraph", "bifmeshio", "bifrostshellnode", "bifrostvisplugin", "Boss", "mayaVnnPlugin"),
        "Arnold": ("mtoa",),
        "XGen": ("xgenToolkit",),
        "MASH": ("MASH",),
        "USD": ("mayaUsdPlugin",),
        "Bullet": ("bullet", "AbcBullet"),
        "Redshift": ("redshift4maya",),
        "Flow": ("Flow.py", "flowWedging.py", "flowRetopology.py"),   # measured: 2-7 s in Maya 2025 / 2026
        "LookdevX": ("LookdevXMaya",),                                # measured: 0.6-2.6 s; pulls in USD
    }

    def __init__(self, tool_config_dir: str | Path):
        """
        Args:
            tool_config_dir: The tool's own config folder (e.g.
                configs/desktop/maya_gate); nothing is created until a launch.
        """
        self._root = Path(tool_config_dir) / self.SUBDIR

    # --- Maya's own list -----------------------------------------------------------

    @staticmethod
    def prefs_file(year: str, app_dir: str | Path | None = None) -> Path:
        """pluginPrefs.mel of Maya `year`; `app_dir` = the environment's
        MAYA_APP_DIR if it sets one (else the default Documents/maya)."""
        base = Path(app_dir) if app_dir else (MayaPaths.get_preferences_root() or Path.home() / "Documents" / "maya")
        return base / year / "prefs" / "pluginPrefs.mel"

    @staticmethod
    def parse_autoload(text: str) -> list[str]:
        """Plug-in names of a pluginPrefs.mel, in its order. A line reads
        evalDeferred("autoLoadPlugin(\\"\\", \\"<name>\\", \\"<plugin>\\")");"""
        names: list[str] = []
        for line in text.splitlines():
            if "autoLoadPlugin(" in line:
                parts = line.split(_QUOTE)
                if len(parts) >= 6 and parts[3] not in names:
                    names.append(parts[3])
        return names

    def autoload_plugins(self, year: str, app_dir: str | Path | None = None) -> list[str]:
        """Plug-ins Maya `year` auto-loads ([] if it has no preferences yet)."""
        prefs = self.prefs_file(year, app_dir)
        try:
            return self.parse_autoload(prefs.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            return []

    @classmethod
    def family_of(cls, plugin: str) -> str:
        """The heavy family `plugin` belongs to ("" = none)."""
        for family, names in cls.HEAVY.items():
            if plugin in names:
                return family
        return ""

    @classmethod
    def heavy_plugins(cls) -> set[str]:
        return {name for names in cls.HEAVY.values() for name in names}

    # --- launch ----------------------------------------------------------------------

    @classmethod
    def blocked_reason(cls, variables: Mapping[str, str]) -> str:
        """Why a launch with `variables` can't be boosted ("" = it can)."""
        if str(variables.get(cls.BLOCKING_VARIABLE, "")).strip():
            return (f"{cls.BLOCKING_VARIABLE} is on in this environment: Maya runs no userSetup, "
                    f"so boost start can’t load plug-ins and stays off.")
        return ""

    def prepare_launch(self, environment: str, year: str, skip: list[str],
                       variables: Mapping[str, str]) -> tuple[dict[str, str], list[str]]:
        """What a boosted launch of Maya `year` needs: (`variables` with the
        loader on PYTHONPATH and its parameters, extra command-line
        arguments). Stores a backup of pluginPrefs.mel first. Call it AFTER
        UserSetupStore.launch_environment(), which builds PYTHONPATH."""
        result = self.attach_loader(variables)
        self._backup_prefs(year, result.get("MAYA_APP_DIR") or None)
        result[self.SKIP_VARIABLE] = os.pathsep.join(skip)
        result[self.REPORT_VARIABLE] = str(self.report_file(year))
        result[self.ENVIRONMENT_VARIABLE] = environment
        return result, [self.FLAG]

    def attach_loader(self, variables: Mapping[str, str]) -> dict[str, str]:
        """`variables` with the loader's folder first on PYTHONPATH — for
        every launch: the loader also measures the startup time. Call it
        AFTER UserSetupStore.launch_environment(), which builds PYTHONPATH."""
        result = dict(variables)
        loader_dir = str(self._write_loader())
        inherited = result.get("PYTHONPATH") or os.environ.get("PYTHONPATH", "")
        entries = [entry for entry in inherited.split(os.pathsep) if entry.strip() and entry != loader_dir]
        result["PYTHONPATH"] = os.pathsep.join([loader_dir] + entries)
        return result

    def launch_log(self) -> "LaunchLog":
        return LaunchLog(self._root / "launches")

    def _write_loader(self) -> Path:
        launch_dir = self._root / "launch"
        launch_dir.mkdir(parents=True, exist_ok=True)
        loader = launch_dir / "userSetup.py"
        # Rewrite only on change: an identical file keeps Maya's trust hash valid.
        if not loader.is_file() or loader.read_text(encoding="utf-8") != _LOADER:
            loader.write_text(_LOADER, encoding="utf-8")
        return launch_dir

    # --- report ----------------------------------------------------------------------

    def report_file(self, year: str) -> Path:
        return self._root / f"report_{year}.json"

    def report(self, year: str) -> dict | None:
        """What the last boosted start of Maya `year` did: {"plugins":
        {name: {"seconds", "status": loaded|skipped|kept|failed, "error"}},
        "seconds", "time", "environment", "notes": [str]} — None if there was none."""
        try:
            data = json.loads(self.report_file(year).read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        return data if isinstance(data, dict) and isinstance(data.get("plugins"), dict) else None

    # --- backups of Maya's list -----------------------------------------------------

    def _backup_dir(self, year: str) -> Path:
        return self._root / "backup" / year

    def backups(self, year: str) -> list[Path]:
        """Stored copies of Maya `year`'s pluginPrefs.mel, newest first."""
        folder = self._backup_dir(year)
        return sorted(folder.glob("pluginPrefs_*.mel"), reverse=True) if folder.is_dir() else []

    def accept_current(self, year: str, app_dir: str | Path | None = None) -> None:
        """Takes Maya `year`'s list as it is now for the reference copy (the
        user removed plug-ins from it on purpose)."""
        self._backup_prefs(year, app_dir, force=True)

    def _backup_prefs(self, year: str, app_dir: str | Path | None, force: bool = False) -> None:
        """Copies pluginPrefs.mel before a boosted launch — unless it equals
        the newest copy, or has LOST plug-ins the newest copy has (a damaged
        list must not push the good copies out; `force` stores it anyway).
        Keeps BACKUPS_KEPT."""
        prefs = self.prefs_file(year, app_dir)
        try:
            content = prefs.read_bytes()
        except OSError:
            return
        existing = self.backups(year)
        if existing and not force:
            newest = existing[0].read_bytes()
            saved = self.parse_autoload(newest.decode("utf-8", "replace"))
            current = set(self.parse_autoload(content.decode("utf-8", "replace")))
            if newest == content or any(name not in current for name in saved):
                return
        folder = self._backup_dir(year)
        folder.mkdir(parents=True, exist_ok=True)
        (folder / f"pluginPrefs_{time.strftime('%Y%m%d_%H%M%S')}.mel").write_bytes(content)
        for old in self.backups(year)[self.BACKUPS_KEPT:]:
            try:
                old.unlink()
            except OSError:
                pass

    def lost_plugins(self, year: str, app_dir: str | Path | None = None) -> list[str]:
        """Plug-ins of the newest backup that Maya `year`'s list no longer has
        — non-empty means the list shrank since the last boosted launch."""
        existing = self.backups(year)
        if not existing:
            return []
        saved = self.parse_autoload(existing[0].read_text(encoding="utf-8", errors="replace"))
        current = set(self.autoload_plugins(year, app_dir))
        return [name for name in saved if name not in current]

    def restore_backup(self, year: str, app_dir: str | Path | None = None) -> bool:
        """Puts the newest backup back as Maya `year`'s pluginPrefs.mel
        (Maya must not be running: it rewrites the file on exit)."""
        existing = self.backups(year)
        if not existing:
            return False
        try:
            shutil.copyfile(existing[0], self.prefs_file(year, app_dir))
        except OSError:
            return False
        return True


class LaunchLog:
    """One small JSON file per launch from Maya Gate: what was started and —
    once Maya's side reported it — how long it took to become ready.

        {"year", "environment", "boosted", "skipped": <count>, "clicked": "2026-10-02 10:15:03",
         "ready_seconds": 18.2,     # added by the loader inside Maya (absent until then / if it never ran)
         "plugin_seconds": 3.6}     # boosted launches: the part spent loading plug-ins
    """

    TIME_VARIABLE = "MSL_GATE_LAUNCH_TIME"   # time.time() of the click
    FILE_VARIABLE = "MSL_GATE_LAUNCH_FILE"   # the launch's file, for the loader to complete
    KEPT = 40

    def __init__(self, folder: str | Path):
        self._folder = Path(folder)

    def start(self, year: str, environment: str, boosted: bool, skipped: int,
              variables: Mapping[str, str]) -> dict[str, str]:
        """Records a launch that is about to happen and returns `variables`
        with what the loader needs to complete the record."""
        result = dict(variables)
        now = time.time()
        try:
            self._folder.mkdir(parents=True, exist_ok=True)
            path = self._folder / f"{time.strftime('%Y%m%d_%H%M%S', time.localtime(now))}_{year}.json"
            path.write_text(json.dumps({"year": year, "environment": environment, "boosted": bool(boosted),
                                        "skipped": int(skipped),
                                        "clicked": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(now))},
                                       indent=1), encoding="utf-8")
            for old in sorted(self._folder.glob("*.json"), reverse=True)[self.KEPT:]:
                old.unlink()
        except OSError:
            return result  # no record, no measurement - the launch itself goes on
        result[self.TIME_VARIABLE] = repr(now)
        result[self.FILE_VARIABLE] = str(path)
        return result

    def entries(self) -> list[dict]:
        """Recorded launches, newest first (unreadable files are skipped)."""
        found = []
        for path in sorted(self._folder.glob("*.json"), reverse=True) if self._folder.is_dir() else []:
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                continue
            if isinstance(data, dict):
                found.append(data)
        return found

    def last_measured(self, environment: str, year: str = "", boosted: bool | None = None) -> dict | None:
        """The newest launch of `environment` that reported its startup time
        (optionally of one Maya `year` / only boosted or only normal ones)."""
        for entry in self.entries():
            if entry.get("environment") != environment or "ready_seconds" not in entry:
                continue
            if year and entry.get("year") != year:
                continue
            if boosted is not None and bool(entry.get("boosted")) != boosted:
                continue
            return entry
        return None
