# tools/desktop/maya_gate/user_setup.py
"""Storage and launch wiring for Maya Gate's per-environment userSetup scripts.

Qt-free on purpose: the tab (user_setup_tab.py) edits, this module stores
and prepares the launch.

How the script reaches Maya: Maya executes EVERY `userSetup.py` it finds on
`sys.path` (verified in maya/app/startup/basic.py, Maya 2020-2026), so a
launch only needs to put a folder holding a `userSetup.py` on PYTHONPATH —
the user's own Documents/maya/.../userSetup.py still runs as usual.

What gets put there is not the edited script itself but a tiny, never-
changing wrapper that exec()s the script:
- Maya runs all userSetup files inside ONE try block, so an exception in
  ours would silently skip every userSetup after it. The wrapper catches
  and prints it instead.
- Maya 2022+ hashes each userSetup file (`safemodecheckhash`) and asks the
  user to trust it again whenever the hash changes. The wrapper's content
  never changes, so editing the script doesn't re-trigger that prompt.
- The wrapper must run under Maya 2020's Python 2.7 too: io.open, no
  f-strings.

msl_tools itself is put on PYTHONPATH by every launch (the folder that
holds the `msl_tools` package: FileSystemManager.PARENT_DIR), so a script
just writes `from msl_tools...` — no sys.path lines, no path variable to
keep in the config (it differs per machine and must not be editable away).
That is what lets the default script be the three-line MENU_SNIPPET.

Layout under the tool's config folder:
    user_setup/<environment>.py                 edited script (what the tab shows)
    user_setup/launch/<environment>/userSetup.py  generated wrapper (on PYTHONPATH)
"""
import os
import re
from pathlib import Path

from msl_tools.msl.core.fs.manager import FileSystemManager

_WRAPPER_TEMPLATE = '''# Generated by MSL Maya Gate - do not edit; edit the "userSetup" tab instead.
import io
import traceback

_msl_gate_script = {script_path!r}
try:
    with io.open(_msl_gate_script, encoding="utf-8") as _msl_gate_file:
        exec(compile(_msl_gate_file.read(), _msl_gate_script, "exec"), globals())
except Exception:
    print("MSL Maya Gate: userSetup script failed: " + _msl_gate_script)
    traceback.print_exc()
'''


# The pre-PYTHONPATH form of MENU_SNIPPET, which carried the package path itself
# (any path) — upgrade_menu_snippet() rewrites it to the short one.
_LEGACY_MENU_SNIPPET = re.compile(
    r"# --- MSL tools: main menu ---\n"
    r"import sys\n"
    r"MSL_PARENT_DIR = r?\"[^\"\n]*\"\n"
    r"if MSL_PARENT_DIR not in sys\.path:\n"
    r"    sys\.path\.insert\(0, MSL_PARENT_DIR\)\n"
    r"from msl_tools\.msl\.startup import bootstrap\n"
    r"bootstrap\(\)\n?")


# Folders an IDE puts on PYTHONPATH for the program it runs (PyCharm's plot / display
# helpers, the pydev debugger). A hub started from the IDE inherits them - they are the
# IDE's business, not Maya's. Matched on the path with forward slashes, lower case.
_IDE_PATH_MARKERS = ("/helpers/pycharm_", "/helpers/pydev", "/plugins/python-ce/helpers", "/plugins/python/helpers")


def _is_ide_path(entry: str) -> bool:
    normalized = entry.replace("\\", "/").lower()
    return any(marker in normalized for marker in _IDE_PATH_MARKERS)


class UserSetupStore:
    """Reads/writes one userSetup script per Maya Gate environment and
    prepares the PYTHONPATH entries that make Maya run it at startup and
    find msl_tools."""

    SUBDIR = "user_setup"
    LAUNCH_SUBDIR = "launch"

    # Loads msl_tools' main menu in Maya. Short because launch_environment()
    # puts msl_tools on PYTHONPATH — the script needs no path of its own.
    MENU_SNIPPET = (
        "# --- MSL tools: main menu ---\n"
        "from msl_tools.msl.startup import bootstrap\n"
        "bootstrap()\n"
    )
    # What an environment's script is until it is first saved (a fresh install):
    # everyone starts with the menu. A script saved empty stays empty.
    DEFAULT_SCRIPT = MENU_SNIPPET

    def __init__(self, tool_config_dir: str | Path):
        """
        Args:
            tool_config_dir: The tool's own config folder (e.g.
                configs/desktop/maya_gate) — supplied by the caller, which
                already knows it; nothing is created until the first write.
        """
        self._root = Path(tool_config_dir) / self.SUBDIR

    # --- scripts -------------------------------------------------------------

    def script_path(self, environment: str) -> Path:
        return self._root / f"{self._slug(environment)}.py"

    def read(self, environment: str) -> str:
        """The environment's script; DEFAULT_SCRIPT while it was never saved."""
        path = self.script_path(environment)
        return path.read_text(encoding="utf-8") if path.is_file() else self.DEFAULT_SCRIPT

    def write(self, environment: str, text: str) -> None:
        path = self.script_path(environment)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    # --- launch --------------------------------------------------------------

    def launch_environment(self, environment: str, variables: dict[str, str]) -> dict[str, str]:
        """Returns `variables` with PYTHONPATH extended for this launch (and
        MAYA_MODULE_PATH: the Maya module of msl_tools in front):

        1. the wrapper's folder — unless the script is blank (then Maya runs
           no userSetup of ours);
        2. the folder holding the msl_tools package — always, so Maya started
           from Maya Gate can `import msl_tools` with no path set anywhere;
        3. the value `variables` sets, else the current process's own, so
           neither the user's nor the system's entries are lost — minus the
           folders an IDE added for itself (a hub run from PyCharm would
           otherwise hand PyCharm's helpers to Maya).

        Entries already present (same folder, any spelling) aren't repeated.
        """
        entries: list[str] = []
        script = self.read(environment)
        if script.strip():
            if not self.script_path(environment).is_file():
                self.write(environment, script)  # the default, first launch: the wrapper needs a file
            entries.append(str(self._write_wrapper(environment)))
        entries.append(str(self.package_parent_dir()))
        own = variables.get("PYTHONPATH")
        inherited = own or os.environ.get("PYTHONPATH", "")
        # What the environment sets itself is passed as it is; only the inherited value is cleaned.
        entries += [entry for entry in inherited.split(os.pathsep)
                    if entry.strip() and (own or not _is_ide_path(entry))]

        unique, seen = [], set()
        for entry in entries:
            key = os.path.normcase(os.path.normpath(entry))
            if key not in seen:
                seen.add(key)
                unique.append(entry)

        result = dict(variables)
        result["PYTHONPATH"] = os.pathsep.join(unique)
        # The Maya module of msl_tools (plug-ins, scripts, icons): first on MAYA_MODULE_PATH, in
        # front of what the environment sets or the hub inherited. Maya adds its own default
        # module folders to this variable itself. A plug-in found this way is trusted — loaded
        # by path from anywhere else, Maya stops on its "untrusted plug-in" question.
        modules = [str(self.maya_module_dir())]
        modules += [entry for entry in (variables.get("MAYA_MODULE_PATH")
                                        or os.environ.get("MAYA_MODULE_PATH", "")).split(os.pathsep)
                    if entry.strip() and os.path.normcase(os.path.normpath(entry))
                    != os.path.normcase(os.path.normpath(modules[0]))]
        result["MAYA_MODULE_PATH"] = os.pathsep.join(modules)
        return result

    @staticmethod
    def maya_module_dir() -> Path:
        """The folder of msl_tools' Maya module (it holds mslTools.mod) — of THIS install."""
        return FileSystemManager.ROOT_DIR / "msl" / "maya_module"

    @staticmethod
    def package_parent_dir() -> Path:
        """The folder that holds the `msl_tools` package (what must be on
        sys.path to import it) — of THIS install."""
        return FileSystemManager.PARENT_DIR

    def _write_wrapper(self, environment: str) -> Path:
        launch_dir = self._root / self.LAUNCH_SUBDIR / self._slug(environment)
        launch_dir.mkdir(parents=True, exist_ok=True)
        wrapper = launch_dir / "userSetup.py"
        content = _WRAPPER_TEMPLATE.format(script_path=str(self.script_path(environment)))
        # Rewrite only on change: an identical file keeps Maya's trust hash valid.
        if not wrapper.is_file() or wrapper.read_text(encoding="utf-8") != content:
            wrapper.write_text(content, encoding="utf-8")
        return launch_dir

    # --- snippets ------------------------------------------------------------

    @staticmethod
    def syntax_error(text: str) -> tuple[int, str] | None:
        """(line, message) of the first syntax error in `text`, or None when
        it compiles. Checked with THIS Python: a script may still fail in an
        older Maya (2020 = Python 2.7) on newer syntax like f-strings."""
        try:
            compile(text, "<userSetup>", "exec")
        except SyntaxError as error:
            return error.lineno or 1, error.msg or "invalid syntax"
        except ValueError as error:  # e.g. a null byte in the source
            return 1, str(error)
        return None

    @classmethod
    def upgrade_menu_snippet(cls, text: str) -> str:
        """`text` with every old-style menu block (the one that set
        MSL_PARENT_DIR / sys.path itself) replaced by MENU_SNIPPET, and
        MENU_SNIPPET kept only once. Text with nothing to fix comes back
        untouched (no reformatting of the user's script)."""
        upgraded = _LEGACY_MENU_SNIPPET.sub(lambda _match: cls.MENU_SNIPPET, text)
        if upgraded == text and text.count(cls.MENU_SNIPPET) <= 1:
            return text
        end = upgraded.find(cls.MENU_SNIPPET) + len(cls.MENU_SNIPPET)
        upgraded = upgraded[:end] + upgraded[end:].replace(cls.MENU_SNIPPET, "")
        # The removed blocks leave blank-line runs behind.
        return re.sub(r"\n{3,}", "\n\n", upgraded).rstrip("\n") + "\n"

    @staticmethod
    def _slug(environment: str) -> str:
        """File-name-safe form of an environment name ("<default>" -> "default")."""
        return re.sub(r"[^A-Za-z0-9_-]+", "", environment) or "default"
