# tools/desktop/maya_gate/user_setup.py
"""Storage and launch wiring for Maya Gate's per-environment userSetup scripts.

Qt-free on purpose: the tab (user_setup_tab.py) edits, this module stores
and prepares the launch.

How the script reaches Maya: Maya executes EVERY `userSetup.py` it finds on
`sys.path` (verified in maya/app/startup/basic.py, Maya 2020-2026), so a
launch only needs to put a folder holding a `userSetup.py` on PYTHONPATH —
the user's own Documents/maya/.../userSetup.py still runs as usual.

What gets put there is not the edited script itself but a tiny, never-
changing wrapper that exec()s the script:
- Maya runs all userSetup files inside ONE try block, so an exception in
  ours would silently skip every userSetup after it. The wrapper catches
  and prints it instead.
- Maya 2022+ hashes each userSetup file (`safemodecheckhash`) and asks the
  user to trust it again whenever the hash changes. The wrapper's content
  never changes, so editing the script doesn't re-trigger that prompt.
- The wrapper must run under Maya 2020's Python 2.7 too: io.open, no
  f-strings.

Layout under the tool's config folder:
    user_setup/<environment>.py                 edited script (what the tab shows)
    user_setup/launch/<environment>/userSetup.py  generated wrapper (on PYTHONPATH)
"""
import os
import re
from pathlib import Path

import msl_tools.msl as msl

_WRAPPER_TEMPLATE = '''# Generated by MSL Maya Gate - do not edit; edit the "userSetup" tab instead.
import io
import traceback

_msl_gate_script = {script_path!r}
try:
    with io.open(_msl_gate_script, encoding="utf-8") as _msl_gate_file:
        exec(compile(_msl_gate_file.read(), _msl_gate_script, "exec"), globals())
except Exception:
    print("MSL Maya Gate: userSetup script failed: " + _msl_gate_script)
    traceback.print_exc()
'''


class UserSetupStore:
    """Reads/writes one userSetup script per Maya Gate environment and
    prepares the PYTHONPATH entry that makes Maya run it at startup."""

    SUBDIR = "user_setup"
    LAUNCH_SUBDIR = "launch"

    def __init__(self, tool_config_dir: str | Path):
        """
        Args:
            tool_config_dir: The tool's own config folder (e.g.
                configs/maya/maya_gate) — supplied by the caller, which
                already knows it; nothing is created until the first write.
        """
        self._root = Path(tool_config_dir) / self.SUBDIR

    # --- scripts -------------------------------------------------------------

    def script_path(self, environment: str) -> Path:
        return self._root / f"{self._slug(environment)}.py"

    def read(self, environment: str) -> str:
        path = self.script_path(environment)
        return path.read_text(encoding="utf-8") if path.is_file() else ""

    def write(self, environment: str, text: str) -> None:
        path = self.script_path(environment)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    # --- launch --------------------------------------------------------------

    def launch_environment(self, environment: str, variables: dict[str, str]) -> dict[str, str]:
        """Returns `variables` with the wrapper's folder prepended to
        PYTHONPATH — or `variables` unchanged when the script is blank.

        PYTHONPATH continues with the value `variables` sets, else the
        current process's own, so neither the user's nor the system's
        entries are lost.
        """
        if not self.read(environment).strip():
            return dict(variables)

        launch_dir = self._write_wrapper(environment)
        inherited = variables.get("PYTHONPATH") or os.environ.get("PYTHONPATH", "")
        result = dict(variables)
        result["PYTHONPATH"] = os.pathsep.join(p for p in (str(launch_dir), inherited) if p)
        return result

    def _write_wrapper(self, environment: str) -> Path:
        launch_dir = self._root / self.LAUNCH_SUBDIR / self._slug(environment)
        launch_dir.mkdir(parents=True, exist_ok=True)
        wrapper = launch_dir / "userSetup.py"
        content = _WRAPPER_TEMPLATE.format(script_path=str(self.script_path(environment)))
        # Rewrite only on change: an identical file keeps Maya's trust hash valid.
        if not wrapper.is_file() or wrapper.read_text(encoding="utf-8") != content:
            wrapper.write_text(content, encoding="utf-8")
        return launch_dir

    # --- snippets ------------------------------------------------------------

    @staticmethod
    def msl_menu_snippet() -> str:
        """Code that loads msl_tools' main menu in Maya — the same thing
        tools/maya/userSetup.py does, pointed at THIS checkout."""
        # msl_tools is a namespace package (no __file__) — go through msl:
        # .../<parent>/msl_tools/msl/__init__.py -> <parent>
        parent_dir = str(Path(msl.__file__).resolve().parents[2])
        return (
            "# --- MSL tools: main menu ---\n"
            "import sys\n"
            f"MSL_PARENT_DIR = r\"{parent_dir}\"\n"
            "if MSL_PARENT_DIR not in sys.path:\n"
            "    sys.path.insert(0, MSL_PARENT_DIR)\n"
            "from msl_tools.msl.startup import bootstrap\n"
            "bootstrap()\n"
        )

    @staticmethod
    def _slug(environment: str) -> str:
        """File-name-safe form of an environment name ("<default>" -> "default")."""
        return re.sub(r"[^A-Za-z0-9_-]+", "", environment) or "default"
